apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeploy-deployment
  namespace: nodejsweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsdeploy
  template:
    metadata:
      labels:
        app: nodejsdeploy
    spec:
      containers:
        - name: nodejsdeploy
          image: himanshu19660/mynodejsapplication:latest  # ✅ corrected spelling
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerhub-secret   # ✅ use your actual secret name
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsdeploy-service
  namespace: nodejsweb
spec:
  selector:
    app: nodejsdeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
