apiVersion: v1
kind: Namespace
metadata:
  name: nodejsweb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsdeploy-deployment
  namespace: nodejsweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsdeploy
  template:
    metadata:
      labels:
        app: nodejsdeploy
    spec:
      containers:
      - name: nodejs-app
        image: himanshu19660/mynodejsappliction:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: nodejsweb
spec:
  selector:
    app: nodejsdeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
